debugging docs-deploy.yml
Signed-off-by: Rieks <RieksJ@users.noreply.github.com>

diff --git a/.github/workflows/docs-deploy.yml b/.github/workflows/docs-deploy.yml
--- a/.github/workflows/docs-deploy.yml
+++ b/.github/workflows/docs-deploy.yml
@@ -9,18 +9,21 @@ on:
 
 jobs:
   deploy:
+    name: Deploy to GitHub Pages
+    runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
         working-directory: docs
-    name: Deploy to GitHub Pages
-    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with:
           node-version: 18
           cache: yarn
+
+      - name: Check for yarn.lock
+        run: test -f yarn.lock || (echo "yarn.lock file not found"; exit 1)
 
       - name: Install dependencies
         run: yarn install --frozen-lockfile
